pub mod builtins;
pub mod execution;
pub mod heap;
pub mod language;
pub mod types;
pub use heap::Heap;
mod small_integer;
mod small_string;
pub use small_integer::SmallInteger;
pub use small_string::SmallString;
